name: hypercp
channels:
  - conda-forge
  - defaults
  - ocdb
dependencies:
  - python
  - pyqt
  - requests
  - tqdm
  - numpy
  - h5py
  - pytz
  - matplotlib
  - scipy
  - pandas
  - pysolar
  - xarray
  - cdsapi
  - netcdf4
  - j6s
  - pytables
  - pyspectral
  - pyqtgraph
  - ocdb-client
  - pip
  - pip:
    - comet_maths
    - punpy
    - fpdf2
    - lmfit