name: Application Testing

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  ApplicationTesting:
    name: Application Tests

    runs-on: ${{ matrix.os }}
    defaults: # Required for conda environment activation
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest'  , 'macos-latest', 'windows-latest' ]

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v7

      - name: 🔧 Setup Environment
        uses: ./.github/actions/SetupEnvironment

      - name: 🔑 Get ECMWF CDS|ADS Credentials
        env:
          CDSAPIRC: ${{ secrets.ECMWF_ADS_CREDENTIALS }}
        run: |
          echo "$CDSAPIRC" > ~/.ecmwf_ads_credentials.json

      - name: 🔑 Get GMAO MERRA2 Credentials
        env:
          NETRC: ${{ secrets.NETRC }}
        run: |
          echo "$NETRC" > ~/.netrc
          chmod 600 "$HOME/.netrc"

      - name: Disable IPv6 for EarthData access on Linux
        if: runner.os == 'Linux'
        run: |
          sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1

      - name: 🧪 Run Tests
        run: |
          python -m unittest Tests.test_filing
          python -m unittest Tests.test_sample_data
